### ISSUE TITLE
include test files and tests in the bundle.

### ISSUE THREAD

**Issue by HinTak** [microsoft/VisualTrueType#18]
I have included all the non-executable files (the release notes, the chm files also, plus the sample ttf and templates) in my opencompiler-port, but it would be better if Microsoft staff do it officially.

Found one bug while testing; the fix is in the pull.

**Comment by paullinnerud** [comment]
I included source of the VTT help file as well as some additional documentation. I will use a different font for tests. Not going to include VTT release note right now since may not always be in alignment.

**Comment by HinTak** [comment]
Yes, I saw the commits and the selawik commit and revert. Vttdemo.ttf is quite useful as it gives different results for each of to switches (except -b -c - cached tables), so if you are going to use a different font, be sure it has all the strange TSI1 , TSI2 etc tables - ie __not__ the release/production version of the font.

**Comment by paullinnerud** [comment]
Unit testing and test font is supported and executed on the Python extension side of the compiler. The Selawik test font includes source and was already in open source and is included in this project.
