### ISSUE TITLE
vttcompile can't find maxp table

### ISSUE THREAD

**Issue by madig** [microsoft/VisualTrueType#19]
Trying to run `vttcompile -a in.ttf out.ttf` where `in.tff` is [in.zip](https://github.com/microsoft/VisualTrueType/files/7316363/in.zip) (compiled from https://github.com/daltonmaag/ubuntu/). It seems to fail getting at the `maxp` table. I'm looking at https://github.com/microsoft/VisualTrueType/blob/7559fcb2d7d560cae62c195d13e5c92d4f7afabc/src/TTFont.cpp#L1929 which passes in a `tag` of 1835104368 (`maxp`) and gets back a zero.

Compiled commit 7559fcb2d7d560cae62c195d13e5c92d4f7afabc on Fedora 34 x86_64, gcc version 11.2.1 20210728 (Red Hat 11.2.1-1)

**Comment by madig** [comment]
Oh boy. I was wondering why the debugger was showing me 64 bit tags inside p inside GetTableOffset...

**Comment by HinTak** [comment]
Do "make CXXFLAGS=-m32" to build for 32-bit and compare/trace.

**Comment by HinTak** [comment]
Pretty sure almost all the "long" in TTFont.* should be int32 instead! Over 300 of them!

**Comment by HinTak** [comment]
Well, the fix is easy but invasive - there are only 7 "long long" in the code, and 800+ long's . Replace all long by int32 (since that's what both 32-bit and 64-bit windows does), except those 7...

**Comment by HinTak** [comment]
Pushed the changes to both pull #9 and opencompiler-port.

**Comment by HinTak** [comment]
@madig thanks for the proof-reading. It is down to under 4800 on opencompiler-port and just over 4400 on pull #17 . I'll have a careful look-through at some point... unfortunately "long" is such common word, and essential part of c/c++ ... there is no clever tricks, like the swprintf macro expansion, to avoid replacing all of it.

**Comment by HinTak** [comment]
I totally agree - I actually tried this approach as a first attempt, but int32_t/uint32_t requires adding <cstdint>, and that brings in a lot of *32* and *64* types which collide with some of the historical portability defines in opentypedefs.h . Besides that requires scattering a few "#include <cstdint>" around. I am trying to do the minimum change, and a balance between "algorithmically minimum" (scripting changes with sed), and try to avoid editing individual lines by hand.

I have gone through the diff against just before the bulk change, and reverted a few more things. Some unfortunately is manual editing, as there is no obvious sed patterns to do.

**Comment by HinTak** [comment]
Hmm, pch.h already includes stdint.h ... maybe I should give it a 2nd try...
