### ISSUE TITLE
Automated Build

### ISSUE THREAD

**Issue by paullinnerud** [microsoft/VisualTrueType#5]
Automate build of VTTCompile using MSBuild.

**Comment by chrissimpkins** [comment]
Are the builds in https://github.com/microsoft/VisualTrueType/actions/workflows/msbuild.yml appropriate for distribution to testers?  If not, is the msbuild.yml build configuration an appropriate reference for documentation of the current build process on Windows?

**Comment by paullinnerud** [comment]
The initial msbuild.yml is just a quick action to build release x64 Windows build. The resulting binary would be fine to test. This is similar to the vttshell tool included with the full VTT downloads https://aka.ms/vtt. We could expand to include debug releases and x86 releases if needed.
